### ISSUE TITLE
[Feature] Add pacman to the toolchain for managing PSP libraries

### ISSUE THREAD

**Issue by sharkwouter** [pspdev/psptoolchain#151]
# Pacman

Last year I put some work into trying to see if we could find a better solution for managing libraries in the toolchain. Back then I found that pacman could offer use the following features:

- Installing libraries
- Updating libraries
- Uninstalling libraries
- Sharing libraries
- Standardized way of building libraries

# What has been completed

The follow have been completed:

- The psp-pacman repo is up at https://github.com/pspdev/psp-pacman/
- The psp-packages repo which host the repository is up at https://github.com/pspdev/psp-packages/
- All libraries apart from pthread-emb and openal-soft have been included in the new repo

# Work waiting to be approved

The following pull requests are open for it: 

- https://github.com/pspdev/psptoolchain/pull/121

# TODO

Now the following things still need to be done:

- [x] Make sure psp-pacman works on MacOS (adressed by https://github.com/pspdev/psp-pacman/pull/12)
- [ ]  Make sure the PSPBUILDs up-to-date with the current state in the psplibraries repo (I could use some help with this. Just look at differences in the sources and patches used in psplibraries versus in the psp-packages repo)
- [x] Automatically build packages added to the psplibraries repo (See https://github.com/pspdev/psp-packages)
- [x] Host the packages in a repo (See https://github.com/pspdev/psp-packages)
- [x] Make psp-pacman use the repo by default (https://github.com/pspdev/psp-pacman/pull/14)

# Impediments

These are issues which are preventing me from making progress on this:

- https://github.com/pspdev/psplibraries/issues/83
- https://github.com/pspdev/psplibraries/issues/84
- https://github.com/pspdev/psp-packages/issues/1 (This one is not quite as critical, but should be resolved at some point)

**Comment by sharkwouter** [comment]
I've updated the issue to reflect the current state. Since the https://github.com/pspdev/psp-packages repo has now been created and the repository is up.

**Comment by sharkwouter** [comment]
Pacman has been added now.
